[package]
name = "opc"
version = "0.1.0"
authors = ["Jacob Payne <info@latrasis.com>"]
description = "A rust implementation of the open pixel control protocol"
license = "MIT"

[dependencies]
byteorder = "0.5.3"

[dev-dependencies]
rand = "0.3.14"
