[package]
name = "opc"
version = "0.1.0"
authors = ["Jacob Payne <info@latrasis.com>"]
description = "A rust implementation of the open pixel control protocol"

[dependencies]
byteorder = "*"

[dev-dependencies]
rand = "*"
